### PR TITLE
add license to README.md

### PR DESCRIPTION
**Pull request by clareluna**
Hi Sam,

My name is Clare Monahan, I'm helping Brook Riggio build the curriculum for the new Code 301. For one of the projects we are asking the students to refactor a previous Code Fellows project. We would like your permission to use your Black History Ipsum as a template to be refactored. If you are comfortable with this, I have added an open MIT license to your README.md file, please merge my PR and let me know we have your consent.

All the best, 
Clare

### CODE REVIEW

**Comment by Jasmineiona** [comment]
Hello Clare. I'm Jasmine Brown. The Black History Ipsum project was my idea. Sam was the JavaScript and Github wizard in my group. I don't mind if the 301 class uses our project as a template. I'd like to see what the 301 students do with it, but I want to maintain a copy of the master without the class' changes. I'm planning on putting an expanded version of the black history Ipsum on the web as a part of my portfolio. If you want to reach out to me directly my email is: jasmineiona@hotmail.com.

**Comment by pnwlady** [comment]
I accepted the request Claire. Students will fork, so it won't effect this repo, right?

**Comment by clareluna** [comment]
Hi Heidi,

Sorry I just saw this email. If you would like we can set the copyright to
you under the MIT copyright. In effect it will allow you to retain the
rights, and you can then send us a message approving the class specifically
to fork your repos and refactor them.

And you are correct, the students will grab a forked repo and only work off
that.

Let me know if that works for you,

Clare

**Comment by Jasmineiona** [comment]
Hello Clare. You did not respond to me. Since the black history ipsum was my idea I believe the copyright should be set to me. Please respond.

**Comment by clareluna** [comment]
Hi Jasmine,

First off let me say I am sorry, I did not realize you had emailed me and
Heidi had also emailed me. My suggestion would be if you guys or you
personally want to retain rights to Black History Ipsum to add your name to
the License, something like

"this project is the the intellectual property of ___ group members____".
Again, you guys do not need to give us rights to use your project as a
template if you dont want to. The project we are trying to make for the 301
is to fork an existing repo, identify places they could add to it, and demo
those to the class.

I am working to make sure I fork the repos first, get permission, then give
class access to my forked repos so that acts as a firewall to ensure no
changes are made to your project itself.

I am also happy to speak with you on the phone if you prefer
(303)-520-4278, and again this is all voluntary, so if you don't want us to
use your project, that is fine.

Thanks,
Clare
---------- Forwarded message ----------

**Comment by pnwlady** [comment]
Jasmine, 

Are you comfortable with the project being shared? You can retain a master on your github account or in Sam's repo. Claire just wants the class to be able to -in their own git repos- work with our project. 

We can just add the bit about copyright to the license doc. And I would like the entire group to be listed. 

Thanks,

Heidi

**Pull request merged**
